# Configuração da porta e chamada da url
server:
  port: 8081
  servlet:
    context-path: /bootcamp

#Configuração Base de dados Postgresql - Docker
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: 123456
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    generate-ddl: true
    hibernate:
      ddl-auto: none

#
application:
  description: Projeto criado para o Bootcamp - Santander
  version: 1.0
